### Default USER API URL
GET http://localhost:3000/user_api/

### Get user by id
GET http://localhost:3000/user_api/user/2/


### Get Users by login and password
GET http://localhost:3000/user_api/users?login=a&password=ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9

### Get Users from API
GET http://localhost:3000/user_api/users

### Post a new user
POST http://localhost:3000/user_api/users/
content-type: application/json

{
    "login": "sample",
    "password": "tetst",
    "right": "USER"
}

### Delete user with ID 4
DELETE http://localhost:3000/user_api/user/2


### Update user with ID 4
PATCH  http://localhost:3000/user_api/user/2
content-type: application/json

{
    "login": "Eliot",
    "password": "BgTimide",
    "right": "USER"
}

