### Default USER API URL
GET http://localhost:3000/user_api/

### Get user by id
GET http://localhost:3000/user_api/user/1/


### Get Users by login and password
GET http://localhost:3000/user_api/users?login=Eliot&password=BgTimide&apiKey=4BD39FF27B8B6C9433C8EBB4F455C

### Get Users from API
GET http://localhost:3000/user_api/users

### Post a new user
POST http://localhost:3000/user_api/users/
content-type: application/json

{
    "login": "sample",
    "password": "test"
}

### Delete user with ID 4
DELETE http://localhost:3000/user_api/user/4


### Update user with ID 4
PATCH  http://localhost:3000/user_api/user/1
content-type: application/json

{
    "login": "Eliot",
    "password": "BgTimide"
}

